---
- name: Add ssh keys
  copy: src={{item}} 
        dest=~/.ssh/{{item|basename}}
  with_fileglob:
    - id_*

- name: Install pip requirements
  pip: requirements=~/{{rpc_repo_dir}}/requirements.txt

- name: Copy rpc_deploy directory
  command: cp -a ~/{{rpc_repo_dir}}/etc/rpc_deploy ~/rpc_deploy
           creates=~/rpc_deploy

- name: Set environment_md5 fact for template
  stat: path=~/rpc_deploy/rpc_environment.yml
  register: environment_version

- name: install rpc user config file
  template: src="{{lab_name or 'default'}}/rpc_user_config.j2"
            dest=~/rpc_deploy/rpc_user_config.yml

- name: Generate passphrases
  command: ~/{{rpc_repo_dir}}/scripts/pw-token-gen.py --file ~/rpc_deploy/user_variables.yml

- name: "template target.sh"
  template: src="{{lab_name or 'default'}}/target.sh.j2"
            dest=~/target.sh 
            mode=0755

- name: Dump deployment host IP to local file
  delegate_to: localhost
  copy: content={{ ansible_ssh_host }}
        dest=~/target.ip
